# Generated by Django 5.0.2 on 2025-04-28 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('daily', 'Daily Report'), ('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('yearly', 'Yearly Report'), ('custom', 'Custom Report')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('transaction_types', models.JSONField(default=list)),
                ('categories', models.JSONField(default=list)),
                ('sort_by', models.CharField(choices=[('date_asc', 'Date (Oldest First)'), ('date_desc', 'Date (Newest First)'), ('amount_asc', 'Amount (Lowest First)'), ('amount_desc', 'Amount (Highest First)'), ('name_asc', 'Name (A-Z)'), ('name_desc', 'Name (Z-A)')], default='date_desc', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'report_type'], name='reports_rep_user_id_f11f57_idx'), models.Index(fields=['user', 'created_at'], name='reports_rep_user_id_9178ae_idx')],
            },
        ),
    ]
